FROM golang:1.24-alpine AS builder

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /build

COPY go.mod ./

RUN go mod download

COPY . .

RUN go build -o /server ./cmd/main.go


FROM alpine:3.23 as app

WORKDIR /app

COPY --from=builder /server /app/server
COPY ./web/ /app/web/

EXPOSE 8080

CMD ["/app/server"]
